apiVersion: v1
kind: ResourceQuota
metadata:
  name: db-quota
  namespace: <Namespace name>
spec:
  hard:
    pods: 10
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi