apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default 
type: Opaque
data:
  username: Y3AyMDIz #cp2023
  database: dHdvZ2U= #twoge
  password: ZWR3aW4yMDIzCg== #edwin2023
  port: NTQzMg== #5432


   

