# To use minikube storge class use the code below.
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: db-storage
#   namespace: <Namespace name>
# provisioner: k8s.io/minikube-hostpath

# To use storage class on AWS EKS Use the code below
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
  namespace: <Namespace name>
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
