apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-vpc
  namespace: default 
spec:
  storageClassName: db-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
