version: '3'
services:
  app:
    container_name: 'twoge'
    build: .
    ports: 
      - "80:80"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://<username>:<password>@<db_host>:5432/<database>
    depends_on:
      db:
        condition: service_healthy
    networks:
      - twoge-networks
  db:
    image: 'postgres'
    container_name: 'twoge-db'
    networks:
      - twoge-networks
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<database>
    healthcheck:
      test: ["CMD","pg_isready","-q","-d","<database>","-U","<username>"]
      timeout: 20s
      retries: 10
  
networks:
  twoge-networks:
    name: twoge-networks
    driver: bridge 

