apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
  namespace: edwin
provisioner: k8s.io/minikube-hostpath

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: db-storage
#   namespace: edwin
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true
