# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: twoge-storage 
#   namespace: edwin
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: twoge-storage
  namespace: edwin
provisioner: k8s.io/minikube-hostpath