apiVersion: v1
kind: Service
metadata:
  name: twoge-service 
  namespace: <Namespace name>
spec:
  selector:
    app: twoge
# Load balancer is for AWS EKS and NodePort is for minikube
  type: LoadBalancer
  # type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

