apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoge
  namespace: edwin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twoge
  template:
    metadata:
      labels:
        app: twoge
    spec:
      containers:
      - name: twoge
        image: epquito/twoge-flask:v1
        resources:
          limits:
            cpu: "0.5"
            memory: 500Gi
          requests:
            cpu: "0.25"
            memory: 2500Mi
#       volumeMounts:
#       - name: data-volume
#         mountPath: /data

        env:
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: twoge-secret
              key: db_url
        readinessProbe:
          httpGet:
            path: /
            port: 80
          successThreshold: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
#      volumes: 
#      - name: data-volume
#        persistentVolumeClaim:
#          claimName: twoge-vpc
